services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: hypermatrix-app:prod
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: ${APP_URL}
      APP_KEY: ${APP_KEY}
      QUEUE_CONNECTION: redis
      # DB
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      HP_LOGIN: ${HP_LOGIN}
      HP_PASS: ${HP_PASS}
      HP_BASE_URL: ${HP_BASE_URL}

      # HORIZON
      HORIZON_DOMAIN: ${HORIZON_DOMAIN}
      HORIZON_PATH: ${HORIZON_PATH}
      HORIZON_PREFIX: ${HORIZON_PREFIX}

      # REDIS
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      # MATRIX
      MATRIX_BASE: ${MATRIX_BASE}
      MATRIX_MANDATORY_NUMBER: ${MATRIX_MANDATORY_NUMBER}
      MATRIX_INTERFACE_NUMBER: ${MATRIX_INTERFACE_NUMBER}
      MATRIX_PASSWORD: ${MATRIX_PASSWORD}
      MATRIX_API_KEY: ${MATRIX_API_KEY}
      MATRIX_RETRY_ATTEMPTS: ${MATRIX_RETRY_ATTEMPTS}
      MATRIX_RETRY_DELAY_MS: ${MATRIX_RETRY_DELAY_MS}
      
      RUN_MIGRATIONS: "true"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "${APP_PORT:-9001}:9001"

  # Service Horizon dédié
  horizon:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: hypermatrix-app:prod
    command: php artisan horizon
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: ${APP_URL}
      APP_KEY: ${APP_KEY}
      QUEUE_CONNECTION: redis
      # DB
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      HP_LOGIN: ${HP_LOGIN}
      HP_PASS: ${HP_PASS}
      HP_BASE_URL: ${HP_BASE_URL}

      # HORIZON
      HORIZON_DOMAIN: ${HORIZON_DOMAIN}
      HORIZON_PATH: ${HORIZON_PATH}
      HORIZON_PREFIX: ${HORIZON_PREFIX}

      # REDIS
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      # MATRIX
      MATRIX_BASE: ${MATRIX_BASE}
      MATRIX_MANDATORY_NUMBER: ${MATRIX_MANDATORY_NUMBER}
      MATRIX_INTERFACE_NUMBER: ${MATRIX_INTERFACE_NUMBER}
      MATRIX_PASSWORD: ${MATRIX_PASSWORD}
      MATRIX_API_KEY: ${MATRIX_API_KEY}
      MATRIX_RETRY_ATTEMPTS: ${MATRIX_RETRY_ATTEMPTS}
      MATRIX_RETRY_DELAY_MS: ${MATRIX_RETRY_DELAY_MS}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  scheduler:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: hypermatrix-app:prod
    command: php artisan schedule:work
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: ${APP_URL}
      APP_KEY: ${APP_KEY}
      QUEUE_CONNECTION: redis
      # DB
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      HP_LOGIN: ${HP_LOGIN}
      HP_PASS: ${HP_PASS}
      HP_BASE_URL: ${HP_BASE_URL}

      # HORIZON
      HORIZON_DOMAIN: ${HORIZON_DOMAIN}
      HORIZON_PATH: ${HORIZON_PATH}
      HORIZON_PREFIX: ${HORIZON_PREFIX}

      # REDIS
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      # MATRIX
      MATRIX_BASE: ${MATRIX_BASE}
      MATRIX_MANDATORY_NUMBER: ${MATRIX_MANDATORY_NUMBER}
      MATRIX_INTERFACE_NUMBER: ${MATRIX_INTERFACE_NUMBER}
      MATRIX_PASSWORD: ${MATRIX_PASSWORD}
      MATRIX_API_KEY: ${MATRIX_API_KEY}
      MATRIX_RETRY_ATTEMPTS: ${MATRIX_RETRY_ATTEMPTS}
      MATRIX_RETRY_DELAY_MS: ${MATRIX_RETRY_DELAY_MS}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: hypermatrix
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 40s
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  redis_data:
