services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: hypermatrix-app:prod
    env_file:
      - .env
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: ${APP_URL}
      # Fournir une APP_KEY valide (base64...)
      APP_KEY: ${APP_KEY}
      # DB
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      # Activer si tu veux migrer en boot (déploiements contrôlés)
      RUN_MIGRATIONS: "true"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "80:80"
    # Pas de volumes de code en prod
    # Optionnel: volume pour logs si tu veux les externaliser
    # volumes:
    #   - app_logs:/var/www/html/storage/logs

  db:
    image: mysql:8
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: hypermatrix
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 40s
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  # app_logs:
